name: projrect_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  flick_video_player: ^0.9.0
  video_player: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets section if you have images in the app
  assets:
    - assets/videos/sample.mp4
    - assets/images.png
    - assets/images/web-developer.jpg
    - assets/images/python_developer.jpg
    - assets/images/Arduino.webp
    - assets/images/Cyber_security.webp

    # Add other image paths here if needed
