name: projrect_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  youtube_player_iframe: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/videos/sample.mp4
    - assets/images/image.png
    - assets/images/web-developer.jpg
    - assets/images/python_developer.jpg
    - assets/images/Arduino.webp
    - assets/images/Cyber_security.webp
    - assets/images/photo.jpg
    - assets/images/photo_2.jpg
    - assets/images/photo_3.jpg
    - assets/videos/just.mp4
    # Add other image paths here if needed
